/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VLayout: typeof import('./components/VLayout.vue')['default']
    VListItem: typeof import('./components/VListItem.vue')['default']
    VScrollbar: typeof import('./components/VScrollbar.vue')['default']
    VSideMenu: typeof import('./components/VSideMenu.vue')['default']
  }
}
