/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Add: typeof import('./components/dialogs/Add.vue')['default']
    BaseLayout: typeof import('./components/BaseLayout.vue')['default']
    ButtonWithTooltip: typeof import('./components/ButtonWithTooltip.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./components/Header.vue')['default']
    List: typeof import('./components/List.vue')['default']
    ListItem: typeof import('./components/ListItem.vue')['default']
    MenuItem: typeof import('./components/MenuItem.vue')['default']
    Meta: typeof import('./components/Meta.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Searchbar: typeof import('./components/Searchbar.vue')['default']
    SideMenu: typeof import('./components/SideMenu.vue')['default']
    StudioExtra: typeof import('./components/StudioExtra.vue')['default']
    Toolbar: typeof import('./components/Toolbar.vue')['default']
    VButton: typeof import('./components/ui/VButton.vue')['default']
    VCard: typeof import('./components/ui/VCard.vue')['default']
    VDialog: typeof import('./components/ui/VGlobalDialog/VDialog.vue')['default']
    VDialogProvider: typeof import('./components/ui/VGlobalDialog/VDialogProvider.vue')['default']
    VInput: typeof import('./components/ui/VInput.vue')['default']
  }
}
