/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DashBoard: typeof import('./components/views/DashBoard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./components/views/Test.vue')['default']
    VCard: typeof import('./components/VCard.vue')['default']
    VDialog: typeof import('./components/VDialog.vue')['default']
    VHeader: typeof import('./components/VHeader.vue')['default']
    VLayout: typeof import('./components/VLayout.vue')['default']
    VList: typeof import('./components/VList.vue')['default']
    VListItem: typeof import('./components/VListItem.vue')['default']
    VMeta: typeof import('./components/VMeta.vue')['default']
    VSearchbar: typeof import('./components/VSearchbar.vue')['default']
    VSideMenu: typeof import('./components/VSideMenu.vue')['default']
    VSnippetList: typeof import('./components/VSnippetList.vue')['default']
    VToolbar: typeof import('./components/VToolbar.vue')['default']
  }
}
